#!/bin/bash
#
# Define the registration token
#SITE_TOKEN="YOUR_SITE_TOKEN_HERE"
#
# Create the registration token file
#echo "$SITE_TOKEN" > /tmp/sentinel_install/com.sentinelone.registration-token
#if [ $? -ne 0 ]; then
#    echo "Error: Failed to create registration token file."
#    exit 1
#fi

# Find the SentinelOne package
pkg_file=$(find /tmp/sentinel_install/ -type f -name "Sentinel-Release-*.pkg" | head -n 1)

# Install the SentinelOne package
/usr/sbin/installer -pkg "$pkg_file" -target /
if [ $? -ne 0 ]; then
    echo "Error: Failed to install the SentinelOne package."
    exit 1
fi

# Remove the temporary installation directory
rm -rf /tmp/sentinel_install
if [ $? -ne 0 ]; then
    echo "Error: Failed to remove temporary installation directory."
    exit 1
fi

echo "Script completed successfully."
